# Large Language Models

+ Harald Puhr
+ 2025-10-22

## Setup

### Load libraries

In [1]:
from chatlas import ChatOpenAI
import pandas as pd

### Define parameters

* `BASE_MODEL` is the model we will use throughout the exercise.
* `OPENAI_API_KEY` is the API key we use to send requests to the OpenAI server.

In [2]:
BASE_MODEL = "gpt-5-nano"  # Replace with your preferred model.
OPENAI_API_KEY = "XXX" # Replace with the OpenAI API key from OLAT.

## Generate dummy data

This code processes a list of customer reviews for a bike product. It creates a
 data frame with the reviews and assigns a unique `Review_ID` to each review.
Variables:

* `reviews`: A Python list containing customer reviews for a bike product.
* `data`: A pandas DataFrame containing the customer reviews and their corresponding Review_IDs.

In [4]:

reviews = [
    "My daughter absolutely loves this bike! Easy to assemble and sturdy.",
    "The bike is well-made and looks great, but it arrived with a scratch.",
    "Perfect size for my 5-year-old son. He rides it every day!",
    "The training wheels are a bit flimsy, but otherwise it's a good bike.",
    "Great value for the price. Assembly was simple and instructions were clear.",
    "My son outgrew his old bike, and this was a perfect upgrade. Highly recommend.",
    "Poor quality materials. The chain fell off after one week of use.",
    "We had trouble with the brakes at first, but customer service was very helpful.",
    "Fantastic bike! My daughter loves the color and design.",
    "The seat could be more comfortable, but it's a nice bike overall.",
]

data = pd.DataFrame({"Customer_Review": reviews})
data["Review_ID"] = range(1, len(data) + 1)
data

                                     Customer_Review  Review_ID
0  My daughter absolutely loves this bike! Easy t...          1
1  The bike is well-made and looks great, but it ...          2
2  Perfect size for my 5-year-old son. He rides i...          3
3  The training wheels are a bit flimsy, but othe...          4
4  Great value for the price. Assembly was simple...          5
5  My son outgrew his old bike, and this was a pe...          6
6  Poor quality materials. The chain fell off aft...          7
7  We had trouble with the brakes at first, but c...          8
8  Fantastic bike! My daughter loves the color an...          9
9  The seat could be more comfortable, but it's a...         10

## Initialize LLM

In [65]:
chat = ChatOpenAI(
    model = BASE_MODEL,
    api_key = OPENAI_API_KEY,
    system_prompt = "You are a helpful assistant that provide trivia on programming languages."
)

## Test LLM

This code initializes a chat session with the Chatlas model and sends a query to
 the model asking "Who created Python?".

In [66]:
chat.chat("Who created Python?", echo = "none")

By inspecting the `chat` object, we get important information about our chat
session witht he OpenAI server:

+ Model type
+ Number of turns
+ Token usage
+ Cost estimate
+ User messages
+ Assistant messages

In [67]:
chat

<Chat OpenAI/gpt-5-nano turns=3 tokens=26/506 $0.0>
  <Turn role='system'>
    <ContentText text='You are a helpful assistant that provide trivia on...'>

  <Turn role='user'>
    <ContentText text='Who created Python?'>

  <Turn role='assistant' tokens=(26, 506, 0) finish_reason='stop' completion=ChatCompletion(id='chatcmpl-CXnVysIpNrGa5eWBS7W37JNIfD2im', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Guido van Rossum, a Dutch programmer. He started the project in December 1989 at CWI in Amsterdam and released Python 0.9.0 in 1991. The name comes from Monty Python’s Flying Circus.', refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=None))], created=1762171194, model='gpt-5-nano-2025-08-07', object='chat.completion.chunk', service_tier='default', system_fingerprint=None, usage=CompletionUsage(completion_tokens=506, prompt_tokens=26, total_tokens=532, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=0, audio_tokens=0, reasoning_tokens=448, rejected_prediction_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0)), obfuscation='pxkShsO6uXHZX8aDKzYdlBCfvR8yQHzDSOMqF8C0hCjqRsgaqGI9CM0KXKxwKk9esR8AEC18T6k9kXgxFdKlB58gHyjH0iRqnM3s7e6gFRt6oXs4mW3o8pzH0Fi9ovSJQwo8H1v7jPxIeXDfAIdtd089fSxqU8rJTWbE64632yEacEYtwHJZE9eKgKseMIJZlodTj2DvfEFunTwlaDhpIE7vkpifVf3Ez2kCoMPoTtl26XMrujbTDuFWqj9aYdsrKjneTA0TX')>
    <ContentText text='Guido van Rossum, a Dutch programmer. He started t...'>

We can extract information regarding the cost and token usage more precisely.

In [68]:
chat.get_tokens()

[{'role': 'user', 'tokens': 26, 'tokens_cached': 0, 'tokens_total': 26},
 {'role': 'assistant', 'tokens': 506, 'tokens_cached': 0, 'tokens_total': 506}]

In [69]:
chat.get_cost()

0.00020370000000000002

We can also separtely extract the chat's messages.

In [21]:
chat.get_last_turn(role='system')

<Turn role='system'>
  <ContentText text='You are a helpful assistant that provide trivia on...'>

In [22]:
chat.get_last_turn(role='user')

<Turn role='user'>
  <ContentText text='Who created Python?'>

In [23]:
chat.get_last_turn(role='assistant')

<Turn role='assistant' tokens=(26, 580, 0) finish_reason='stop' completion=ChatCompletion(id='chatcmpl-CXmnOOy5owAMP9FZLK7K91mpq2NTZ', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Python was created by Guido van Rossum. He started the project in December 1989 at CWI in the Netherlands, with the first public release (Python 0.9.0) in 1991. The name was chosen as a tribute to Monty Python’s Flying Circus.', refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=None))], created=1762168430, model='gpt-5-nano-2025-08-07', object='chat.completion.chunk', service_tier='default', system_fingerprint=None, usage=CompletionUsage(completion_tokens=580, prompt_tokens=26, total_tokens=606, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=0, audio_tokens=0, reasoning_tokens=512, rejected_prediction_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0)), obfuscation='KGSHSiDcALzCgIB5clCXQY6PgYngdeqYirgKGLHF809rxUQEjxUfu7xyieAWMhJOUKumREZHaT2elG0FvljMknXrxvMcTGrTlQjpVzfkQzsw0Zt4JzG7T9wIbQEveYO16nKf07bHCOOWvwTihkvHiq2MtYyv5kvxPk2gaLEf328g5jLBNpdPa2mGRIJ1pL5GAWFUgydjYKHZnUFgRGLmRHWH5K6DAV4EvijdFT54En3n9UBKEiRrGsbLQenN2VtKNf29EQfUba9eVizOlxT9z4WaacVThbxbxABbwSbbyK3FZbdYsDW')>
  <ContentText text='Python was created by Guido van Rossum. He started...'>

## Create a function to query the LLM

### Function: Get response from Chatlas chat model

This function facilitates interaction with the Chatlas chat model by generating a response based on the provided system and user prompts.

#### Parameters:

* `system`: A string that serves as the system prompt to initialize the chat model.
* `user`: A string that represents the user prompt to which the chat model will generate a response.

#### Returns:

A string containing the response generated by the chat model.

In [70]:
def get_response(system: str, user: str):
    chat = ChatOpenAI(
        model = BASE_MODEL,
        api_key = OPENAI_API_KEY,
        system_prompt = system
    )
    chat.chat(user, echo = "none")
    response = chat.get_last_turn(role = "assistant")
    response = str(response)
    return response

## Classification of customer reviews

### Define system prompt

In [71]:

system_prompt = """
You are a classifier for customer reviews. Review each customer review whether
it is negative or positive. Return only a number between 1 (negative) and 5
(positive).
"""

### Test the function

In [39]:
data.loc[0, "Customer_Review"]

'My daughter absolutely loves this bike! Easy to assemble and sturdy.'

In [72]:
get_response(system = system_prompt, user = data.loc[0, "Customer_Review"])

'5'

### Apply the function to each review

In [73]:

data1 = data.assign(
    Classification = data["Customer_Review"].apply(lambda review: get_response(system_prompt, review))
)
data1

                                     Customer_Review  Review_ID Classification
0  My daughter absolutely loves this bike! Easy t...          1              5
1  The bike is well-made and looks great, but it ...          2              4
2  Perfect size for my 5-year-old son. He rides i...          3              5
3  The training wheels are a bit flimsy, but othe...          4              4
4  Great value for the price. Assembly was simple...          5              5
5  My son outgrew his old bike, and this was a pe...          6              5
6  Poor quality materials. The chain fell off aft...          7              1
7  We had trouble with the brakes at first, but c...          8              4
8  Fantastic bike! My daughter loves the color an...          9              5
9  The seat could be more comfortable, but it's a...         10              4

## Structured data

LLMs are quite good at finding structure in unstructured input like text,
images, etc. Though not always perfect, this can be a very helpful way to reduce
the amount of manual work needed to extract information from a large amount of
text or documents.

The example below is based on the `chatlas` [documentation](https://posit-dev.github.io/chatlas/structured-data/sentiment-analysis.html).

In [40]:
from pydantic import BaseModel, Field

In [41]:
class Sentiment(BaseModel):
    """Extract the sentiment scores of a given text. Sentiment scores should sum to 1."""

    positive_score: float = Field(
        description="Positive sentiment score, ranging from 0.0 to 1.0"
    )

    negative_score: float = Field(
        description="Negative sentiment score, ranging from 0.0 to 1.0"
    )

    neutral_score: float = Field(
        description="Neutral sentiment score, ranging from 0.0 to 1.0"
    )

In [75]:
chat = ChatOpenAI(
    model = BASE_MODEL,
    api_key = OPENAI_API_KEY,
    system_prompt = "You are a helpful assistant that provide trivia on programming languages."
)

In [84]:
chat.chat_structured(data.loc[0, "Customer_Review"], data_model = Sentiment, echo = "none")

Sentiment(positive_score=0.8, negative_score=0.05, neutral_score=0.15)

In [85]:
chat.get_last_turn(role = "assistant").contents[0]

```json
{
  "positive_score": 0.8,
  "negative_score": 0.05,
  "neutral_score": 0.15
}
```

## Defining roles

The `system_prompt` is the primary place for you to influence the behavior of
the model. A well-crafted system prompt steers the model toward delightful,
accurate, and safe answers. Keep in mind that:

+ There is one `system_prompt` per `Chat` instance.
+ It's sent to the model with every request.
+ It typically remains fixed during a conversation and is invisible to the end user.

The example below is based on the `chatlas` [documentation](https://posit-dev.github.io/chatlas/get-started/system-prompt.html).

In [95]:
roles = ["customer service agent", "technical support", "sales representative"]

for r in roles:
    chat = ChatOpenAI(
        model = BASE_MODEL,
        api_key = OPENAI_API_KEY,
        system_prompt = f"You act as a {r} in our firm. Provide a short summary of how our firm should respond to the customer feedback."
    )
    chat.chat(data.loc[0, "Customer_Review"], echo = "none")
    print("Role: " + r)
    print(chat.get_last_turn(role = "assistant").contents[0].text)

Role: customer service agent
Here are ready-to-use response options you can tailor to your brand voice. They acknowledge the positives, show appreciation, and invite further engagement.

1) Short public reply (social media or review)
- “So great to hear! We’re thrilled your daughter loves the bike and that it was easy to assemble and feels sturdy. If you’d like, share a photo of her riding it—we’d love to feature it. And we’re here if you need any tips or accessories.”

2) Customer service email/template
- “Hi [Name],
Thank you for taking the time to share your feedback. We’re delighted to hear that your daughter loves the bike and that it was easy to assemble and feels sturdy. If there’s anything else you need—spare parts, sizing guidance, or safety tips—please reply and we’ll be happy to help. If you have a moment, we’d greatly appreciate a quick review to help other families make a great choice. Feel free to attach a photo too if you’d like us to feature it.
Best regards,
[Your Name/Team]”

3) Gentle upsell or cross-sell note
- “We’re glad you’re happy with the bike! If you’re looking to complete the setup, we offer kid-friendly helmets, bells, lights, and a maintenance kit that pair nicely with this model. Want recommendations tailored to your bike?”

4) Safety and ongoing support message
- “Wonderful to hear! A quick safety check after the first rides is a good habit—tire pressure, brakes, and chain. If you’d like, we can send a short checklist or a link to our setup video. And if you ever need replacement parts or adjustments, we’re here to help.”

Tips for personalizing the response
- Use the customer’s name if available.
- Reference the specific positives they mentioned (easy to assemble, sturdy).
- Invite further engagement: ask for a photo, a quick review, or if they need tips or accessories.
- Keep the tone warm and helpful, not pushy.
- Provide a simple next step (reply for tips, share a photo, leave a review, or ask about accessories).

If you’d like, I can tailor one version to your exact brand voice (casual, professional, or premium) or draft versions for a specific channel (email, chat, and social media).
Role: technical support
Great news to hear! Here are ready-to-use responses and a small plan you can follow to handle this feedback well.

1) Quick customer-facing reply (short, suitable for chat or a single email)
- “That’s wonderful to hear—thank you for sharing! We’re thrilled your daughter loves the bike and that it was easy to assemble and feels sturdy. If you’re comfortable, we’d love to feature your feedback (and a photo, if you have one) on our site or social channels. Just reply yes or let us know your preference. We’re here if you need any help with maintenance or accessories.”

2) Email-length response (more formal)
- “Hi [Name], thank you so much for the kind words. We’re delighted to hear your daughter loves the bike and that you found it easy to assemble and sturdy in use. We designed it with ease of assembly and durability in mind, so it’s great to hear that feedback is on target. If you’d be willing, we’d love to feature your experience as a customer story on our website or social media (with your permission). If you have a photo of your daughter riding the bike, please attach it or let us know if you’d prefer not to include photos. And of course, if you need any help with maintenance or parts, we’re here to assist. Best regards, [Your Name/Team]”

3) Social media reply (short and friendly)
- “So happy to hear this! We’re glad your daughter loves the bike and that it was easy to assemble and sturdy. Thank you for the wonderful feedback—if you’d like us to feature your story (with your permission), just say so. We’re here if you need anything else!”

4) Follow-up actions you can take internally
- Log the feedback as positive sentiment for the bike product and note “easy to assemble” and “sturdy” as confirmed strengths.
- Consider requesting a testimonial: with customer consent, use their quote in marketing or product pages. Include a simple consent note: “Would you like us to feature your feedback publicly? Yes/No” and offer to anonymize if desired.
- If appropriate, invite for a photo testimonio: “If you’re comfortable, please send a photo of your daughter with the bike to accompany the testimonial.”
- Offer proactive support: remind them we’re available for maintenance, spare parts, or any future gear.

5) Privacy and consent guidance
- Always obtain explicit permission before using quotes or photos publicly.
- Offer an option to keep the testimonial anonymous if preferred.

Example combined reply you can paste:
- “That’s wonderful to hear—thank you for sharing! We’re thrilled your daughter loves the bike and that it was easy to assemble and sturdy. If you’re comfortable, we’d love to feature your feedback on our website or social channels (with your permission). You can reply ‘Yes, you may share’ and, if you like, attach a photo of her riding. If not, we’ll simply appreciate your kind words. And of course, we’re here if you need any help with maintenance or parts.”

If you’d like, I can tailor one or two of these templates to your brand voice and the specific channel you’ll use (email, chat, or social).
Role: sales representative
Here are ready-to-use response options and next steps you can use to handle this positive feedback.

A. Quick chat reply (immediate, friendly)
- “That’s wonderful to hear! We’re thrilled your daughter loves the bike and that assembly was easy and the bike feels sturdy. If you need any maintenance tips or parts, just reply here. If you’re comfortable, we’d love to feature your feedback as a short testimonial—let us know and we’ll share how to proceed.”

B. Follow-up email template
Subject: Thank you for the kind words about [Bike Model]

Body:
Hi [Name],
Thank you so much for sharing how much your daughter loves the bike. We’re delighted to hear that it was easy to assemble and feels sturdy—that’s exactly what we aim for.
If you have a moment, we’d love to feature your feedback as a testimonial on our site (and we can include a photo if you’d like). Of course, we’ll only use what you approve.
If you’re ever in need of maintenance tips or parts, we’re here to help. As a token of our appreciation, we can offer a small discount on your next purchase—just let us know if you’d like that.
Thanks again for choosing us and for taking the time to share your experience.
Best regards,
[Your Name]
[Company]

C. Social media reply (public post/comment)
- “So great to hear! Thanks for sharing—glad your daughter loves the bike and that it was easy to assemble. If you’re comfortable, we’d love to feature your feedback as a quick testimonial (and a photo, if you’d like). Just reply here with permission.”

D. How to solicit and handle testimonials (internal steps)
- Ask for explicit consent to use the feedback as a testimonial (and photo if applicable).
- If approved, collect a short written testimonial and optional photo, then publish on the website and social channels with consent.
- Add the customer to a lightweight nurture list (e.g., occasional tips, accessory recommendations, or loyalty offers).
- Offer a small token (e.g., maintenance tips guide, discount on next purchase) if you have a standard customer appreciation practice.

E. Suggested upsell/cross-sell (optional)
- Maintenance kit (chain oil, tire pump, patch kit)
- Helmet and protective gear
- Spare inner tube or tire
- Accessory upgrades (bell, kickstand, lighting for safety)

If you’d like, I can tailor these templates to your brand voice or provide a single, concise message for all channels.
Role: product manager
Great feedback to build on. Here’s a concise plan and ready-to-use templates you can deploy across channels.

What to reply and why
- Acknowledge quickly and warmly: reinforces customer trust.
- Highlight the specific positives (easy to assemble, sturdy) that your product team aimed for.
- Invite them to share more (review, photo) and offer further help (parts, accessories, safety tips).
- Seek consent to use their words as a testimonial (respect privacy and consent).
- Keep the tone short, friendly, and family-focused.

Response options you can copy/paste

1) Customer support email or message
Subject: Thanks for the kind words about the bike!

Hi [Name],

Thank you so much for sharing this—it's wonderful to hear your daughter loves the bike, and that it was easy to assemble and feels sturdy. We design with families in mind, so feedback like yours really means a lot to us.

If you have a moment, would you consider leaving a quick review at [link]? It helps other families make great choices too. If you’re comfortable, we’d also love to feature your comment as a testimonial on our site. And if you have a photo of your daughter with the bike, we’d be grateful to share it with permission.

If you need any spare parts, accessories, or care tips, we’re here to help.

Warm regards,
[Your Name]
[Company]

2) Public social media reply (e.g., Facebook, Instagram)
Thanks for sharing, [Name]! We’re thrilled your daughter loves the bike and that it was easy to assemble and sturdy. That’s exactly what we aim for. If you’re open to it, we’d love to feature your comment as a testimonial—would you mind? And if you have a photo, feel free to share it and we’ll tag you (with your permission).

3) Review-site comment or direct message
Awesome to hear, [Name]! We’re glad the bike was easy to assemble and feels sturdy. If you have a moment, please leave a short review here: [link]. If you’re comfortable, we’d also love to use your feedback as a testimonial (with your permission). Thanks again for sharing!

Optional optional add-ons
- Ask a clarifying follow-up: “What age/height is your daughter? Any features you especially appreciate or suggestions for improvement?” This can help product teams and future iterations.
- Offer next steps: “Would you like maintenance tips or accessories (helmet, pump, reflectors) recommended for this model?”
- Photo request: “If you’re comfortable, please share a photo and we may feature it with your permission.”

Internal actions for the product/marketing team
- Capture this as a positive testimonial opportunity; request consent for use on the site and social channels.
- If the customer provides a photo, add to a testimonial gallery with consent.
- Flag feedback as validation of key value propositions: ease of assembly, sturdiness.
- Consider using the sentiment in a quarterly “customer wins” snippet for the product team.

Key tone guidelines
- Warm, grateful, family-friendly.
- Focus on the user benefit (ease, safety, durability) rather than generic praise.
- Keep it concise and action-oriented (offer review, testimonial, photo).

If you’d like, I can tailor these templates to your brand voice (more formal, more playful, etc.) or craft a short one-line social response you can drop in real-time.